name: MattMG
description: OG's minigames.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: net.og_mc.mattmg.MattMG
depend: [CloudGame]

commands:
    koth:
        description: KOTH command
        usage: /koth <command>

    lms:
        description: LMS command
        usage: /lms <command>

permissions:
    mattmg.admin:
        description: Allows managing of MattKOTH.
