name: MattKOTH
description: King of the hill minigame.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: net.og_mc.mattkoth.MattKOTHPlugin
depend: [WorldGuard]

commands:
    arena:
        description: Allows management of arenas
        permission: cloudgame.admin
        usage: /arena <subcommand> [args]

    koth:
        description: KOTH command
        usage: /koth <command>

permissions:
    mattkoth.admin:
        description: Allows managing of MattKOTH.
