name: MattMG
description: OG's minigames.
version: $version
author: AlbireoX
website: http://og-mc.net/

main: net.og_mc.mattmg.MattMG
depend: [CloudGame, WorldGuard]

commands:
    arena:
        description: Allows management of arenas
        permission: cloudgame.admin
        usage: /arena <subcommand> [args]

    koth:
        description: KOTH command
        usage: /koth <command>

    lms:
        description: LMS command
        usage: /lms <command>

permissions:
    mattmg.admin:
        description: Allows managing of MattKOTH.
